FROM alpine:3.20@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:be115df99f44cc3be78491be4ed7c5586e8687d9659a89eab1d8f6924a2cc2f0

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
