FROM alpine:3.19@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48 as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:69fa2a7afdb9fd265c336222287a6d27346b29455bbe25329a405dec5891907e

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
